#!/usr/bin/env node
// Regenerates dist/index.html from data/metrics.json so the published
// artifact stays reproducible from its source data.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const data = JSON.parse(readFileSync(new URL("./data/metrics.json", import.meta.url), "utf8"));

function escapeHtml(s) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function metricRow(m) {
  const delta = String(m.delta ?? "");
  const cls = delta.startsWith("-") ? "down" : delta.startsWith("+") ? "up" : "";
  return `        <tr>
          <td>${escapeHtml(m.label)}</td>
          <td class="num">${escapeHtml(m.value)}</td>
          <td class="num delta ${cls}">${escapeHtml(delta)}</td>
        </tr>`;
}

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ops Weekly</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    background: #f6f7f9;
    color: #1c1e21;
    display: grid;
    place-items: center;
    min-height: 100vh;
    padding: 24px;
  }
  main {
    width: 100%;
    max-width: 560px;
    background: #ffffff;
    border: 1px solid #e3e6ea;
    border-radius: 12px;
    padding: 28px 32px;
  }
  h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: -0.01em; }
  p.week { margin: 0 0 20px; color: #6b7280; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; font-size: 14px; }
  th {
    text-align: left; font-weight: 600; color: #6b7280;
    border-bottom: 1px solid #e3e6ea; padding: 8px 4px;
  }
  td { padding: 10px 4px; border-bottom: 1px solid #f0f2f4; }
  tr:last-child td { border-bottom: none; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .up { color: #067647; }
  .down { color: #b42318; }
  footer { margin-top: 20px; font-size: 12px; color: #9ca3af; }
  @media (prefers-color-scheme: dark) {
    body { background: #101214; color: #e6e8eb; }
    main { background: #17191c; border-color: #26292e; }
    th, p.week { color: #9aa1ab; }
    td { border-bottom-color: #22262b; }
  }
</style>
</head>
<body>
<main>
  <h1>${escapeHtml(data.title)}</h1>
  <p class="week">Week ${escapeHtml(data.week)} · fictional demo data</p>
  <table>
    <thead>
      <tr><th>Metric</th><th class="num">Value</th><th class="num">&Delta; vs last week</th></tr>
    </thead>
    <tbody>
${data.metrics.map(metricRow).join("\n")}
    </tbody>
  </table>
  <footer>Generated by build.mjs from data/metrics.json</footer>
</main>
</body>
</html>
`;

mkdirSync("dist", { recursive: true });
writeFileSync(join("dist", "index.html"), html);
console.log(`[weekly-ops-report] wrote dist/index.html (${html.length} bytes, ${data.metrics.length} metrics)`);
